-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 11:52:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client_type` (
  `id_client_type` INT NOT NULL,
  `client_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id_client_type`),
  UNIQUE INDEX `id_client_type_UNIQUE` (`id_client_type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id_client` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `passport` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `id_client_type` INT NOT NULL,
  PRIMARY KEY (`id_client`, `id_client_type`),
  INDEX `fk_client_client_type1_idx` (`id_client_type` ASC) VISIBLE,
  UNIQUE INDEX `id_client_UNIQUE` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_client_client_type1`
    FOREIGN KEY (`id_client_type`)
    REFERENCES `mydb`.`client_type` (`id_client_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`credit_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`credit_type` (
  `id_creditType` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `persent` DOUBLE NULL,
  `term` INT NULL,
  PRIMARY KEY (`id_creditType`),
  UNIQUE INDEX `id_creditType_UNIQUE` (`id_creditType` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`credit` (
  `id_credit` INT NOT NULL,
  `sum` DOUBLE NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `id_credit_type` INT NOT NULL,
  `id_client` INT NOT NULL,
  PRIMARY KEY (`id_credit`, `id_credit_type`, `id_client`),
  INDEX `fk_credit_creditType1_idx` (`id_credit_type` ASC) VISIBLE,
  INDEX `fk_credit_client1_idx` (`id_client` ASC) VISIBLE,
  UNIQUE INDEX `id_credit_UNIQUE` (`id_credit` ASC) VISIBLE,
  CONSTRAINT `fk_credit_creditType1`
    FOREIGN KEY (`id_credit_type`)
    REFERENCES `mydb`.`credit_type` (`id_creditType`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_credit_client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`currency` (
  `id_currency` INT NOT NULL,
  `currency_name` VARCHAR(45) NULL,
  `currency_code` VARCHAR(5) NULL,
  PRIMARY KEY (`id_currency`),
  UNIQUE INDEX `id_currency_UNIQUE` (`id_currency` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deposit_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deposit_type` (
  `id_deposit_type` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `persent` VARCHAR(45) NULL,
  `term` INT NULL,
  `replenishment` TINYINT NULL,
  `early_withdrawal` TINYINT NULL,
  PRIMARY KEY (`id_deposit_type`),
  UNIQUE INDEX `id_deposit_type_UNIQUE` (`id_deposit_type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deposit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deposit` (
  `id_deposit` INT NOT NULL,
  `initial_amount` DOUBLE NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `id_deposit_type` INT NOT NULL,
  `id_client` INT NOT NULL,
  PRIMARY KEY (`id_deposit`, `id_deposit_type`, `id_client`),
  INDEX `fk_deposit_deposit_type1_idx` (`id_deposit_type` ASC) VISIBLE,
  INDEX `fk_deposit_client1_idx` (`id_client` ASC) VISIBLE,
  UNIQUE INDEX `id_deposit_UNIQUE` (`id_deposit` ASC) VISIBLE,
  CONSTRAINT `fk_deposit_deposit_type1`
    FOREIGN KEY (`id_deposit_type`)
    REFERENCES `mydb`.`deposit_type` (`id_deposit_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_deposit_client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job_title` (
  `id_job_title` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_job_title`),
  UNIQUE INDEX `id_job_title_UNIQUE` (`id_job_title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `id_department` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id_department`),
  UNIQUE INDEX `id_department_UNIQUE` (`id_department` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bank_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bank_employee` (
  `id_employee` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `phone` VARCHAR(10) NULL,
  `id_job_title` INT NOT NULL,
  `id_department` INT NOT NULL,
  PRIMARY KEY (`id_employee`, `id_job_title`, `id_department`),
  INDEX `fk_bank_employee_job_title1_idx` (`id_job_title` ASC) VISIBLE,
  INDEX `fk_bank_employee_department1_idx` (`id_department` ASC) VISIBLE,
  UNIQUE INDEX `id_employee_UNIQUE` (`id_employee` ASC) VISIBLE,
  CONSTRAINT `fk_bank_employee_job_title1`
    FOREIGN KEY (`id_job_title`)
    REFERENCES `mydb`.`job_title` (`id_job_title`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bank_employee_department1`
    FOREIGN KEY (`id_department`)
    REFERENCES `mydb`.`department` (`id_department`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `id_account` INT NOT NULL,
  `account` VARCHAR(15) NULL,
  `start_date` DATE NULL,
  `id_currency` INT NOT NULL,
  `id_client` INT NOT NULL,
  `id_employee` INT NOT NULL,
  PRIMARY KEY (`id_account`, `id_currency`, `id_client`, `id_employee`),
  INDEX `fk_account_currency1_idx` (`id_currency` ASC) VISIBLE,
  INDEX `fk_account_client1_idx` (`id_client` ASC) VISIBLE,
  INDEX `fk_account_bank_emploee1_idx` (`id_employee` ASC) VISIBLE,
  UNIQUE INDEX `id_account_UNIQUE` (`id_account` ASC) VISIBLE,
  CONSTRAINT `fk_account_currency1`
    FOREIGN KEY (`id_currency`)
    REFERENCES `mydb`.`currency` (`id_currency`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_account_client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_account_bank_emploee1`
    FOREIGN KEY (`id_employee`)
    REFERENCES `mydb`.`bank_employee` (`id_employee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`operation_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operation_type` (
  `id_operation_type` INT NOT NULL,
  `operation_typecol` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_operation_type`),
  UNIQUE INDEX `id_operation_type_UNIQUE` (`id_operation_type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operations` (
  `id_operations` INT NOT NULL,
  `sum` DOUBLE NULL,
  `operation_date` VARCHAR(45) NULL,
  `id_operation_type` INT NOT NULL,
  `id_account` INT NOT NULL,
  PRIMARY KEY (`id_operations`, `id_operation_type`, `id_account`),
  INDEX `fk_operations_operation_type_idx` (`id_operation_type` ASC) VISIBLE,
  INDEX `fk_operations_account1_idx` (`id_account` ASC) VISIBLE,
  UNIQUE INDEX `id_operations_UNIQUE` (`id_operations` ASC) VISIBLE,
  CONSTRAINT `fk_operations_operation_type`
    FOREIGN KEY (`id_operation_type`)
    REFERENCES `mydb`.`operation_type` (`id_operation_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_operations_account1`
    FOREIGN KEY (`id_account`)
    REFERENCES `mydb`.`account` (`id_account`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`card` (
  `id_card` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `end_date` DATE NULL,
  `online_transactions` TINYINT NULL,
  `day_limits` DOUBLE NULL,
  `account_id_account` INT NOT NULL,
  PRIMARY KEY (`id_card`, `account_id_account`),
  INDEX `fk_card_account1_idx` (`account_id_account` ASC) VISIBLE,
  UNIQUE INDEX `id_card_UNIQUE` (`id_card` ASC) VISIBLE,
  CONSTRAINT `fk_card_account1`
    FOREIGN KEY (`account_id_account`)
    REFERENCES `mydb`.`account` (`id_account`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salary` (
  `id_salary` INT NOT NULL,
  `salary_sum` DOUBLE NULL,
  `bonus` DOUBLE NULL,
  `id_employee` INT NOT NULL,
  PRIMARY KEY (`id_salary`, `id_employee`),
  INDEX `fk_salary_bank_employee1_idx` (`id_employee` ASC) VISIBLE,
  UNIQUE INDEX `id_salary_UNIQUE` (`id_salary` ASC) VISIBLE,
  CONSTRAINT `fk_salary_bank_employee1`
    FOREIGN KEY (`id_employee`)
    REFERENCES `mydb`.`bank_employee` (`id_employee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
